elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
  command: elasticsearch
  ports:
   - "9200:9200"
   - "9300:9300"

logstash:
  image: docker.elastic.co/logstash/logstash:6.6.0
  hostname: "logstash"
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
   - ./logstash/config:/etc/logstash/conf.d
  ports:
   - "5000:5000"
  links:
   - elasticsearch


kibana:
  image: docker.elastic.co/kibana/kibana:6.6.0
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
   - "5601:5601"
  links:
   - elasticsearch 
